inherit_from: .rubocop_todo.yml

# Offense count: 1
Security/Eval:
  Exclude:
    - 'bin/*'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/AsciiComments:
  Enabled: false

Style/Copyright:
  Notice: 'Copyright (\(c\) )?2[0-9]{3} .+'
  AutocorrectNotice: "# Copyright (c) 2018 FINFEX <danil@brandymint.ru>\n"
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: true
  VersionAdded: '0.30'

AllCops:
  Exclude:
    - utils/*
    - vendor/bundle/**/*
